[project]
name = "dotpusher"
version = "0.1.0"
description = "Dotpusher is a declarative method for synchronizing local files or directories with remote ones using git."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "argcomplete"
]
