#!/usr/bin/env zsh
# ┌─┐┬  ┬┌─┐┌─┐┌─┐┌─┐
# ├─┤│  │├─┤└─┐├┤ └─┐
# ┴ ┴┴─┘┴┴ ┴└─┘└─┘└─┘
#--------------------------------------------
# (c) maarutan   https://github.com/maarutan

###############
## variables ##
###############
EXPLORE="yazi"
ROOTEXPLORE="yazi"

EDITOR="nvim"
ROOTEDITOR="nvim"

######################
## change directory ##
######################
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"

############
## system ##
############
alias cls="clear && exec $(basename $SHELL)"
alias nzsh="cd $ZSH_CONFIG; nvim $ZSH_CONFIG/init"
alias ex="exit"
alias pg="ping google.com"
alias th="touch"
alias mkd="mkdir"
alias rm!="rm -rf"
alias rm="rm -r"
alias ll="eza -l -g --icons"
alias la='eza -a --icons --color'
alias lt='eza --tree --icons --color'
alias ls='eza --icons --color=auto'
alias e=$"EXPLORE"
alias re="sudo -E \${ROOTEXPLORE}"
alias n=$"EDITOR"
alias rn="sudo -E \${ROOTEDITOR}"
alias cpp="copypath"

###########
## utils ##
###########
alias walchoice="$HOME/wallpapers/.choise.sh"
alias gay="$HOME/.suckless/scripts/gay.sh"
alias hzsh="nvim $HOME/.zsh/.zsh_history"
alias matrix="unimatrix -b -s 95  -c blue"
alias neo="$HOME/.config/neofetch/.startFetch.sh"
alias bfetch="$HOME/.suckless/scripts/bestfetch.sh"
alias fetch="$HOME/.suckless/scripts/fetch.sh"
alias pwall="$HOME/.suckless/scripts/PicWall.sh"
alias clock="peaclock"
alias goo="/usr/bin/go"
# alias
